## 数组的索引和切片

1. 索引默认从0开始，第一个元素索引为0，第二个元素索引为1，依此类推。

2. 前闭后开规则，默认含首不含尾。

3. -n指反方向第n个数。

4. 修改切片元素时原数组的元素也会相应改变。

In [1]:
import numpy as np
arr = np.arange(10)
print('以此数组为例:', arr)

slice_one = arr[:5] # 提取单个元素去掉冒号即可:arr[4]
print('索引从0到4的切片:', slice_one)

slice_two = arr[4:7]
print('索引从4到6的切片:', slice_two)

slice_three = arr[0:10:3]  # 前两个数可省略：arr[::3] 
print('索引从0到9且步长为3的切片', slice_three)

slice_four = arr[:-5]
print('索引从0到4的切片:', slice_four)

slice_four[0] = 99
print('修改切片元素后原数组随之改变:', arr)

以此数组为例: [0 1 2 3 4 5 6 7 8 9]
索引从0到4的切片: [0 1 2 3 4]
索引从4到6的切片: [4 5 6]
索引从0到9且步长为3的切片 [0 3 6 9]
索引从0到4的切片: [0 1 2 3 4]
修改切片元素后原数组随之改变: [99  1  2  3  4  5  6  7  8  9]


In [2]:
arr = np.arange(1, 10).reshape(3, 3)
print(f"二维数组:\n{arr}")

print(f"行索引从1开始(第2行),列索引取到2(第3列但不包含):\n{arr[1:, :2]}")

二维数组:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
行索引从1开始(第2行),列索引取到2(第3列但不包含):
[[4 5]
 [7 8]]


以下面的三维数组为例，该数组三个维度的轴长分别为2, 3, 4，意味着:

第一个维度包含两个二维子数组，第二个维度包含三个一维子数组，第三个维度包含四个整数。（依次去掉最外层中括号来看）

In [3]:
arr = np.random.randint(1, 10, size=(2, 3, 4))

print(f"三维数组:\n{arr}")

for i in (0, 1):
    print(f"第一维度索引{i}指代的元素:\n{arr[i, :, :]}")

三维数组:
[[[8 3 7 5]
  [9 2 8 3]
  [4 7 1 5]]

 [[9 6 6 1]
  [2 4 6 5]
  [6 3 4 7]]]
第一维度索引0指代的元素:
[[8 3 7 5]
 [9 2 8 3]
 [4 7 1 5]]
第一维度索引1指代的元素:
[[9 6 6 1]
 [2 4 6 5]
 [6 3 4 7]]


In [4]:
for i in (0, 1, 2):
    print(f"第二维度索引{i}指代的元素():\n{arr[:, i, :]}")

第二维度索引0指代的元素():
[[8 3 7 5]
 [9 6 6 1]]
第二维度索引1指代的元素():
[[9 2 8 3]
 [2 4 6 5]]
第二维度索引2指代的元素():
[[4 7 1 5]
 [6 3 4 7]]


In [5]:
for i in (0, 1, 2, 3):
    print(f"第三维度索引{i}指代的元素:\n{arr[:, :, i]}")

第三维度索引0指代的元素:
[[8 9 4]
 [9 2 6]]
第三维度索引1指代的元素:
[[3 2 7]
 [6 4 3]]
第三维度索引2指代的元素:
[[7 8 1]
 [6 6 4]]
第三维度索引3指代的元素:
[[5 3 5]
 [1 5 7]]


<video controls style="width: 100%;">
  <source src="http://szmspython.oss-cn-hangzhou.aliyuncs.com/%E5%91%A8%E4%B8%80%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA%26%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/%E4%B8%89%E4%BD%8D%E6%95%B0%E7%BB%84%E7%9A%84%E7%B4%A2%E5%BC%95%E4%B8%8E%E5%88%87%E7%89%87.mp4" type="video/mp4">
</video>

<style>
  video {
    max-width: 100%;
    height: auto;
  }
</style>

高维数组的切片可用省略号：

In [6]:
print(f"第一维度从第二个元素开始:\n{arr[1:, ...]}")  # 等价于 arr[1:, :, :]

print(f"第一维度第一个子数组中第一列:\n{arr[0, ..., :1]}")  # 等价于 arr[0, :, :1]

第一维度从第二个元素开始:
[[[9 6 6 1]
  [2 4 6 5]
  [6 3 4 7]]]
第一维度第一个子数组中第一列:
[[8]
 [9]
 [4]]


用逻辑条件来筛选满足条件的元素，筛选后的数组会被展平为一维数组：

In [7]:
arr = np.arange(12).reshape((3, 4))
print(f"以此数组为例:\n{arr}")

print(f"大于6的元素:{arr[arr > 6]}")

print(f"返回布尔值:\n{arr > 6}")


以此数组为例:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
大于6的元素:[ 7  8  9 10 11]
返回布尔值:
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]


返回满足条件的元素索引：

In [8]:
arr = np.random.randint(4, size=(3, 3))
print(f"以此二维数组为例:\n{arr}")

print(f"非零元素的索引(分维度):\n{np.nonzero(arr)}")

print(f"元素小于均值的索引:\n{np.nonzero(arr < np.mean(arr))}")


以此二维数组为例:
[[1 1 1]
 [2 1 1]
 [3 1 0]]
非零元素的索引(分维度):
(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))
元素小于均值的索引:
(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 1, 2, 1, 2], dtype=int64))


以坐标形式返回元素索引：

In [9]:
ind = np.nonzero(arr < 6)

list_of_coordinates = list(zip(ind[0], ind[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


::: {.callout-note}

遇到不认识的函数或模块时，例如上述示例代码的`zip()`可以使用`help(zip())`查询函数或模块的信息以及示例代码。

如果想要了解某个特定模块的函数，例如numpy的array函数，可以使用`numpy.info(numpy.array)`，也可以使用缩写`np.info(np.array)`

:::

## 数组的基本运算

数组上的算术运算符按元素应用。


In [10]:
a = np.array([(20,30),(40,50)])
b = np.arange(2,6).reshape(2,2)

print(f"数组a:\n{a}")
print(f"数组b:\n{b}")

print(f"加法运算:\n{np.add(a, b)}")
# 等价于a + b

print(f"减法运算:\n{np.subtract(a, b)}")
# 等价于a - b

print(f"乘法运算:\n{np.multiply(a, b)}")
# 等价于a * b

print(f"除法运算:\n{np.divide(a, b)}")
# 等价于a / b

print(f"平方运算:\n{np.square(b)}")
# 等价于b**2

数组a:
[[20 30]
 [40 50]]
数组b:
[[2 3]
 [4 5]]
加法运算:
[[22 33]
 [44 55]]
减法运算:
[[18 27]
 [36 45]]
乘法运算:
[[ 40  90]
 [160 250]]
除法运算:
[[10. 10.]
 [10. 10.]]
平方运算:
[[ 4  9]
 [16 25]]


矩阵（二维数组）乘积运算用`@`或`.dot()`：

::: {.callout-note}

计算矩阵A和B的乘积时，新矩阵第i行第j列的元素为矩阵A第i行元素和矩阵B第j列元素的乘积和，所以需要A矩阵的列数和矩阵B的行数相同。

:::

In [11]:
A = np.array([(1, 2),(3, 4)])
B = np.array([(3, 2, 1),(1, 1, 1)])

print(f"数组A:\n{A}")
print(f"数组B:\n{B}")

print(f"矩阵的乘积:\n{A@B}")
# 等价于A.dot(B)

数组A:
[[1 2]
 [3 4]]
数组B:
[[3 2 1]
 [1 1 1]]
矩阵的乘积:
[[ 5  4  3]
 [13 10  7]]


聚合函数的运算（可以指定轴）：

In [12]:
arr = np.array([(1, 2), (3, 4)])
print(f"对数组进行聚合函数的运算:\n{arr}")

print("数组元素求和:", arr.sum())

print("数组元素每列求和:", arr.sum(axis=0))  # 行求和:axis = 1

print("数组元素最小值:", arr.min())

print("数组元素每列最小值:", arr.min(axis=0)) 

对数组进行聚合函数的运算:
[[1 2]
 [3 4]]
数组元素求和: 10
数组元素每列求和: [4 6]
数组元素最小值: 1
数组元素每列最小值: [1 2]


## 数组的排序、反转和去重

对元素进行排序/反转，以一维、二维数组为例：


In [13]:
x = np.array([7, 2, 5, 3, 6, 4, 9, 1, 8])
print(f"一维数组:{x}")

print(f"排序:{np.sort(x)}")


print(f"反转:{np.flip(x)}")


print(f"利用切片方式反转,步长为-1:{x[::-1]}")


一维数组:[7 2 5 3 6 4 9 1 8]
排序:[1 2 3 4 5 6 7 8 9]
反转:[8 1 9 4 6 3 5 2 7]
利用切片方式反转,步长为-1:[8 1 9 4 6 3 5 2 7]


In [14]:
y = np.array([[7, 2, 5], [3, 6, 4], [9, 1, 8]])
print(f"二维数组:\n{y}")

print(f"排序:\n{np.sort(y)}")

print(f"反转:\n{np.flip(y)}")

print(f"仅反转子数组顺序:\n{np.flip(y, axis=0)}")

y[:,1] = np.flip(y[:,1])
print(f"仅反转第二列:\n{y}")

二维数组:
[[7 2 5]
 [3 6 4]
 [9 1 8]]
排序:
[[2 5 7]
 [3 4 6]
 [1 8 9]]
反转:
[[8 1 9]
 [4 6 3]
 [5 2 7]]
仅反转子数组顺序:
[[9 1 8]
 [3 6 4]
 [7 2 5]]
仅反转第二列:
[[7 1 5]
 [3 6 4]
 [9 2 8]]


去重复值：

In [15]:
arr = np.array([1, 2, 2, 5, 7, 7, 8, 9, 9, 12, 14])
print(f"原数组:{arr}")

print(f"去重后:{np.unique(arr)}")

unique_arr, indices_list = np.unique(arr, return_index=True)
print(f"去重数组的索引:{indices_list}")

原数组:[ 1  2  2  5  7  7  8  9  9 12 14]
去重后:[ 1  2  5  7  8  9 12 14]
去重数组的索引:[ 0  1  3  4  6  7  9 10]


## 数组的展平、拼接、堆叠、拆分

展平数组可用`flatten()`或`ravel()`。

::: {.callout-note}
使用`flatten`时，对展平数组的更改不会影响原数组，使用`ravel`时，数组的更改会影响原数组。

:::

In [16]:
arr = np.arange(6).reshape(2, 3)
print(f"展平前:\n{arr}")

arr_one = arr.flatten()
print(f"使用flatten展平后:\n{arr_one}")

arr_one[0] = 99
print(f"修改元素:\n{arr_one}")

print(f"原数组不变:\n{arr}")

展平前:
[[0 1 2]
 [3 4 5]]
使用flatten展平后:
[0 1 2 3 4 5]
修改元素:
[99  1  2  3  4  5]
原数组不变:
[[0 1 2]
 [3 4 5]]


In [17]:
arr_two = arr.ravel()
print(f"使用ravel展平后:\n{arr_two}")

arr_two[0] = 99
print(f"修改元素:\n{arr_two}")

print(f"原数组改变:\n{arr}")

使用ravel展平后:
[0 1 2 3 4 5]
修改元素:
[99  1  2  3  4  5]
原数组改变:
[[99  1  2]
 [ 3  4  5]]


拼接和堆叠数组：

::: {.callout-note}
垂直堆叠和拼接需要列数相同，水平堆叠需要行数相同。

:::

In [18]:
a = np.array([(1, 2),(3, 4)])
b = np.ones((3, 2), dtype=np.int_)
c = np.zeros((1, 2), dtype=np.int_)

print(f"数组a:\n{a}")
print(f"数组b:\n{b}")
print(f"数组c:\n{c}")

print(f"拼接三个数组:\n{np.concatenate((a, b, c))}")

print(f"等价于垂直堆叠三个数组:\n{np.vstack((a, b, c))}")

print(f"水平堆叠数组a和数组a:\n{np.hstack((a, a))}")

数组a:
[[1 2]
 [3 4]]
数组b:
[[1 1]
 [1 1]
 [1 1]]
数组c:
[[0 0]]
拼接三个数组:
[[1 2]
 [3 4]
 [1 1]
 [1 1]
 [1 1]
 [0 0]]
等价于垂直堆叠三个数组:
[[1 2]
 [3 4]
 [1 1]
 [1 1]
 [1 1]
 [0 0]]
水平堆叠数组a和数组a:
[[1 2 1 2]
 [3 4 3 4]]


拆分数组：

In [19]:
arr = np.arange(1, 21).reshape(2, 10)
print(f"以此数组为例:\n{arr}")

print(f"拆分为2个形状相同的数组(相当于从第5列开始拆分):\n{np.hsplit(arr, 2)}")

print(f"从第3列,第7列之后开始拆分:\n{np.hsplit(arr, (3, 7))}")

以此数组为例:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
拆分为2个形状相同的数组(相当于从第5列开始拆分):
[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])]
从第3列,第7列之后开始拆分:
[array([[ 1,  2,  3],
       [11, 12, 13]]), array([[ 4,  5,  6,  7],
       [14, 15, 16, 17]]), array([[ 8,  9, 10],
       [18, 19, 20]])]
