NumPy（Numerical Python）是一个开源的Python科学计算库，是Python中用于科学计算和数据分析的核心库之一。它包含多维数组和矩阵数据结构的运算，提供了高性能的多维数组对象ndarray（N-dimensional array）以及处理这些数组的各种函数，提供了高效的数组操作功能，使得处理大规模数据集变得更加高效和便捷。

##  NumPy的安装和导入

安装 NumPy ：

`conda install numpy` 或者 `pip install numpy`

导入 NumPy ：

In [12]:
import numpy as np

使用 NumPy 缩短导入的名称np，可以提高代码的可读性

## NumPy中的核心对象：ndarray
 
ndarray是NumPy中最重要的对象，它是N 维数组的简写，可以是一维数组、二维数组或更高维度的数组。


In [23]:
print("这是一个一维数组:")
np.array((1, 2, 3))


这是一个一维数组:


array([1, 2, 3])

In [22]:
print("这是一个2*3的二维数组:")
np.array([(1, 2, 3),(4, 5, 6)])

这是一个2*3的二维数组:


array([[1, 2, 3],
       [4, 5, 6]])

相对于一维数组，二维数组多了一个维度，示例代码中的二维数组包含两个子数组（也称为行）：[1,2,3]和[4,5,6]，一个子数组代表一个行向量。

ndarray中的元素可以是任意数据类型，包括整数、浮点数、复数等。数据类型由dtype（data type）对象来描述。

## 创建NumPy数组

要创建 NumPy 数组，可以使用函数`np.array()`将序列转换为数组。

::: {.callout-note}
对象只能是一个，例如`((),(),...)`，不能是多个序列：`(),(),...`。

:::


In [3]:
import numpy as np
a = np.array(((1, 2, 3),(4, 5, 6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

创建一个元素都为0的数组（默认元素类型为float64，可以通过dtype进行设置）：

In [4]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

创建一个元素全为1的3*3矩阵，数值类型为整型：

In [5]:
np.ones((3,3), dtype=np.int_)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

创建一个3*3单位矩阵（对角线元素为1）：

In [6]:
np.eye(3, 3, dtype = np.int_)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

创建一个空数组，元素的初始内容会随机生成，可以设置dtype参数：

In [7]:
np.empty((2,3), dtype = np.float_)

array([[0., 0., 0.],
       [0., 0., 0.]])

创建一个等差数列型的一维数组：

`np.arange()`第一个参数start代表起始值，默认从0开始，第二个参数stop代表结束值，但结束值不包含在数组中。第三个参数step为步长，即相邻元素的差值。

In [25]:
print("创建一个值域从0-9,步长为2的数组:")
np.arange(0, 10, 2)

创建一个值域从0-9,步长为2的数组:


array([0, 2, 4, 6, 8])

In [26]:
print("只含一个参数时,默认初始索引为0,步长为1:")
np.arange(4)

只含一个参数时,默认初始索引为0,步长为1:


array([0, 1, 2, 3])

In [27]:
print("创建一个包含6个元素,值域从0到10的整型数组:") 
np.linspace(0, 10, num = 6, dtype = np.int_) 

创建一个包含6个元素,值域从0到10的整型数组:


array([ 0,  2,  4,  6,  8, 10])

创建随机数组：

In [30]:
print("2*2随机数组:")
np.random.random((2, 2))

2*2随机数组:


array([[0.88814558, 0.18417615],
       [0.75345853, 0.71616192]])

创建随机整型数组：

In [29]:
np.random.randint(5, size=(2, 3))

array([[0, 1, 1],
       [2, 4, 2]])

基于已有的数组复制得到新数组：

In [10]:
a = np.arange(4)
c = a.copy()
c

array([0, 1, 2, 3])

## NumPy支持的数据类型

1. 布尔类型（bool）：表示True或False的布尔值，设置`dtype = np.bool_`即可。
2. 整数类型（int）：包括有符号和无符号的整数，如int_、int8、int16、int32、int64、uint8、uint16、uint32、uint64等，u意为unsigned，无符号，表示只能为正数。
3. 浮点数类型（float）：表示浮点数，包括float16、float32、float64(float_)等。
4. 复数类型（complex）：表示复数，包括complex64、complex128(complex_)等。
5. 字符串类型（string）：表示固定长度的字符串，如S10表示长度为10的字符串。
6. Unicode类型（unicode）：表示固定长度的Unicode字符串，如U10表示长度为10的Unicode字符串。
7. 日期和时间类型（datetime）：表示日期和时间，包括datetime64、timedelta64等。

## 数组的形状、维度和大小

在 NumPy 中，维度称为轴。以下面这个二维数组为例，它的第一个轴的长度为2（行），第二个轴长度为3（列）。


In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(f"以此数组为例:\n{a}")

print(f"数组的维度是:{a.ndim}")

print(f"数组的形状是:{a.shape}")

print(f"数组一共包含{a.size}个元素")

以此数组为例:
[[1 2 3]
 [4 5 6]]
数组的维度是:2
数组的形状是:(2, 3)
数组一共包含6个元素
